In [244]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from dotenv import load_dotenv
import os

In [245]:
load_dotenv("../.env")
census_key = os.getenv("CENSUS_API_KEY")

In [246]:
education_data = pd.read_csv('../data/Education/education_data.csv')

In [247]:
unemployment_data = pd.read_csv('../data/Unemployment/unemployment_data.csv')
unemployment_data

,Year,FIPS_Code,County,Labor_Force_Participation_Rate,Unemployment_Rate,Rural_Urban_Continuum_Code_2023
0,2019,54001,Barbour County,52.6,7.6,9
1,2019,54003,Berkeley County,65.4,6.0,2
2,2019,54005,Boone County,40.3,10.6,3
3,2019,54007,Braxton County,52.0,14.4,8
4,2019,54009,Brooke County,55.5,3.8,3
...,...,...,...,...,...,...
270,2023,54101,Webster County,41.0,9.6,9
271,2023,54103,Wetzel County,46.6,5.8,7
272,2023,54105,Wirt County,48.1,3.3,3
273,2023,54107,Wood County,55.5,5.6,3
274,2023,54109,Wyoming County,38.5,5.6,8

In [248]:
poverty_data = pd.read_csv('../data/Poverty and Income/poverty_and_income.csv')
poverty_data

,Year,FIPS_Code,County,Poverty_Percent_All_Ages,Poverty_Percent_Age_0_17,Median_Household_Income
0,2019,54001,Barbour County,20.8,30.8,38459
1,2019,54003,Berkeley County,12.2,18.2,62515
2,2019,54005,Boone County,23.1,32.2,40739
3,2019,54007,Braxton County,22.0,36.9,41466
4,2019,54009,Brooke County,13.2,17.9,51496
...,...,...,...,...,...,...
270,2023,54101,Webster County,22.1,32.4,42061
271,2023,54103,Wetzel County,16.6,16.7,53341
272,2023,54105,Wirt County,18.3,30.4,54688
273,2023,54107,Wood County,14.8,19.0,56193
274,2023,54109,Wyoming County,22.6,26.0,48038

In [249]:
marital_data = pd.read_csv('../data/Marital Status/marital_status.csv')
marital_data

     Year  FIPS_Code           County  Pct_Never_Married  Pct_Divorced
0    2019      54001   Barbour County               48.3           8.0
1    2019      54003  Berkeley County               51.9           5.2
2    2019      54005     Boone County               53.4           8.7
3    2019      54007   Braxton County               54.6           7.7
4    2019      54009    Brooke County               49.7           8.5
..    ...        ...              ...                ...           ...
270  2023      54101   Webster County               54.3           8.6
271  2023      54103    Wetzel County               49.1           9.6
272  2023      54105      Wirt County               57.8          10.4
273  2023      54107      Wood County               48.6           7.4
274  2023      54109   Wyoming County               55.2           9.2

[275 rows x 5 columns]

In [250]:
df = pd.read_csv('../data/Medicare Part D Opioid Prescribing Rates - by Geography/2023/OMT_MDCR_RY25_P04_V10_Y23_GEO.csv')
df

,Year,Prscrbr_Geo_Lvl,Prscrbr_Geo_Cd,Prscrbr_Geo_Desc,RUCA_Cd,Breakout_Type,Breakout,Tot_Prscrbrs,Tot_Opioid_Prscrbrs,Tot_Opioid_Clms,Tot_Clms,Opioid_Prscrbng_Rate,Opioid_Prscrbng_Rate_5Y_Chg,Opioid_Prscrbng_Rate_1Y_Chg,LA_Tot_Opioid_Clms,LA_Opioid_Prscrbng_Rate,LA_Opioid_Prscrbng_Rate_5Y_Chg,LA_Opioid_Prscrbng_Rate_1Y_Chg
0,2023,National,NaN,National,NaN,Totals,Overall,1379131.0,796960.0,59311234.0,1.614516e+09,3.67,-1.01,-0.21,5266348.0,8.88,-2.91,-0.49
1,2023,National,NaN,National,NaN,Rural/Urban,Rural,150022.0,96471.0,10433987.0,2.765332e+08,3.77,-1.04,-0.20,859739.0,8.24,-2.81,-0.47
2,2023,National,NaN,National,NaN,Rural/Urban,Urban,1228080.0,699913.0,48835671.0,1.337145e+09,3.65,-1.01,-0.21,5063859.0,10.37,-2.70,-0.46
3,2023,State,1.0,Alabama,NaN,Totals,Overall,17808.0,9741.0,1661292.0,3.058605e+07,5.43,-1.47,-0.26,101471.0,6.11,-2.25,-0.38
4,2023,State,2.0,Alaska,NaN,Totals,Overall,3034.0,1880.0,73416.0,1.812674e+06,4.05,-1.77,-0.34,9244.0,12.59,-6.04,-0.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
328885,2013,ZIP,99921.0,Alaska:Prince of Wales-Hyder:99921,10.0,Totals,Overall,4.0,4.0,265.0,3.228000e+03,8.21,NaN,NaN,45.0,16.98,NaN,NaN
328886,2013,ZIP,99922.0,Alaska:Prince of Wales-Hyder:99922,10.0,Totals,Overall,2.0,1.0,NaN,1.510000e+02,NaN,NaN,NaN,NaN,NaN,NaN,NaN
328887,2013,ZIP,99925.0,Alaska:Prince of Wales-Hyder:99925,10.0,Totals,Overall,7.0,6.0,641.0,4.644000e+03,13.80,NaN,NaN,160.0,24.96,NaN,NaN
328888,2013,ZIP,99926.0,Alaska:Prince of Wales-Hyder:99926,10.0,Totals,Overall,1.0,1.0,38.0,4.970000e+02,7.65,NaN,NaN,NaN,NaN,NaN,NaN
328889,2013,ZIP,99929.0,Alaska:Wrangell:99929,10.0,Totals,Overall,7.0,7.0,448.0,5.824000e+03,7.69,NaN,NaN,91.0,20.31,NaN,NaN

In [251]:
county_df = df[df['Prscrbr_Geo_Lvl'] == 'County']
county_df

,Year,Prscrbr_Geo_Lvl,Prscrbr_Geo_Cd,Prscrbr_Geo_Desc,RUCA_Cd,Breakout_Type,Breakout,Tot_Prscrbrs,Tot_Opioid_Prscrbrs,Tot_Opioid_Clms,Tot_Clms,Opioid_Prscrbng_Rate,Opioid_Prscrbng_Rate_5Y_Chg,Opioid_Prscrbng_Rate_1Y_Chg,LA_Tot_Opioid_Clms,LA_Opioid_Prscrbng_Rate,LA_Opioid_Prscrbng_Rate_5Y_Chg,LA_Opioid_Prscrbng_Rate_1Y_Chg
171,2023,County,1001.0,Alabama:Autauga,NaN,Totals,Overall,87.0,55.0,23338.0,230839.0,10.11,-1.39,-0.15,2210.0,9.47,-5.50,-1.20
172,2023,County,1003.0,Alabama:Baldwin,NaN,Totals,Overall,703.0,401.0,70191.0,1204318.0,5.83,-0.86,0.12,3591.0,5.12,-2.11,0.14
173,2023,County,1005.0,Alabama:Barbour,NaN,Totals,Overall,37.0,18.0,993.0,77733.0,1.28,-1.65,-0.11,25.0,2.52,-2.03,-0.96
174,2023,County,1007.0,Alabama:Bibb,NaN,Totals,Overall,79.0,38.0,4293.0,140994.0,3.04,-0.69,-0.34,277.0,6.45,-7.89,-0.51
175,2023,County,1009.0,Alabama:Blount,NaN,Totals,Overall,43.0,24.0,3595.0,137302.0,2.62,-2.27,-0.29,62.0,1.72,-1.56,0.22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
309094,2013,County,72149.0,Puerto Rico:Villalba,NaN,Rural/Urban,Urban,25.0,22.0,3465.0,131844.0,2.63,NaN,NaN,58.5,1.69,NaN,NaN
309095,2013,County,72151.0,Puerto Rico:Yabucoa,NaN,Rural/Urban,Urban,39.0,27.0,5015.0,240887.0,2.08,NaN,NaN,54.0,1.08,NaN,NaN
309096,2013,County,72153.0,Puerto Rico:Yauco,NaN,Rural/Urban,Urban,87.0,75.0,5178.0,250867.0,2.06,NaN,NaN,81.0,1.56,NaN,NaN
309097,2013,County,78010.0,Virgin Islands:St. Croix,NaN,Rural/Urban,Urban,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN
309098,2013,County,78030.0,Virgin Islands:St. Thomas,NaN,Rural/Urban,Urban,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN

In [252]:
west_virginia_counties = county_df[county_df['Prscrbr_Geo_Desc'].str.contains('West Virginia')]

west_virginia_counties = west_virginia_counties[
    (west_virginia_counties['Year'] >= 2019) &
    (west_virginia_counties['Year'] <= 2023)
]

west_virginia_counties

,Year,Prscrbr_Geo_Lvl,Prscrbr_Geo_Cd,Prscrbr_Geo_Desc,RUCA_Cd,Breakout_Type,Breakout,Tot_Prscrbrs,Tot_Opioid_Prscrbrs,Tot_Opioid_Clms,Tot_Clms,Opioid_Prscrbng_Rate,Opioid_Prscrbng_Rate_5Y_Chg,Opioid_Prscrbng_Rate_1Y_Chg,LA_Tot_Opioid_Clms,LA_Opioid_Prscrbng_Rate,LA_Opioid_Prscrbng_Rate_5Y_Chg,LA_Opioid_Prscrbng_Rate_1Y_Chg
3124,2023,County,54001.0,West Virginia:Barbour,NaN,Totals,Overall,39.0,27.0,2864.0,107812.0,2.66,-0.61,0.13,155.0,5.41,-0.16,-1.46
3125,2023,County,54003.0,West Virginia:Berkeley,NaN,Totals,Overall,305.0,170.0,11181.0,370917.0,3.01,-1.79,-0.50,997.0,8.92,-3.74,-1.84
3126,2023,County,54005.0,West Virginia:Boone,NaN,Totals,Overall,59.0,37.0,7048.0,143244.0,4.92,-0.87,-0.64,114.0,1.62,-1.80,-0.56
3127,2023,County,54007.0,West Virginia:Braxton,NaN,Totals,Overall,21.0,12.0,1629.0,47547.0,3.43,-1.37,0.27,70.0,4.30,-0.76,0.97
3128,2023,County,54009.0,West Virginia:Brooke,NaN,Totals,Overall,27.0,15.0,1280.0,60692.0,2.11,-2.03,-0.34,22.0,1.72,-1.17,0.35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130088,2019,County,54101.0,West Virginia:Webster,NaN,Rural/Urban,Urban,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN
130089,2019,County,54103.0,West Virginia:Wetzel,NaN,Rural/Urban,Urban,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN
130090,2019,County,54105.0,West Virginia:Wirt,NaN,Rural/Urban,Urban,10.0,8.0,636.0,27170.0,2.34,-4.80,-0.07,12.0,1.89,-6.05,NaN
130091,2019,County,54107.0,West Virginia:Wood,NaN,Rural/Urban,Urban,343.0,195.0,25194.0,633676.0,3.98,-2.17,-1.05,2082.0,8.26,3.56,-1.96
130092,2019,County,54109.0,West Virginia:Wyoming,NaN,Rural/Urban,Urban,29.0,24.0,4940.0,133361.0,3.70,NaN,-1.19,NaN,NaN,NaN,NaN

In [253]:
df_opioid = west_virginia_counties [west_virginia_counties['Breakout'] == 'Overall']

columns_to_keep = [
    'Year',
    'Prscrbr_Geo_Cd',
    'Prscrbr_Geo_Desc',
    'LA_Opioid_Prscrbng_Rate',        # Context
    'LA_Opioid_Prscrbng_Rate_1Y_Chg'  # TARGET
]

df_opioid = df_opioid[columns_to_keep]
df_opioid = df_opioid.rename(columns={
    'Prscrbr_Geo_Cd': 'FIPS_Code',
    'Prscrbr_Geo_Desc': 'County',
    'LA_Opioid_Prscrbng_Rate': 'LA_Opioid_Rate'
})
df_opioid

,Year,FIPS_Code,County,LA_Opioid_Rate,LA_Opioid_Prscrbng_Rate_1Y_Chg
3124,2023,54001.0,West Virginia:Barbour,5.41,-1.46
3125,2023,54003.0,West Virginia:Berkeley,8.92,-1.84
3126,2023,54005.0,West Virginia:Boone,1.62,-0.56
3127,2023,54007.0,West Virginia:Braxton,4.30,0.97
3128,2023,54009.0,West Virginia:Brooke,1.72,0.35
...,...,...,...,...,...
123758,2019,54101.0,West Virginia:Webster,1.92,-1.85
123759,2019,54103.0,West Virginia:Wetzel,3.04,-1.70
123760,2019,54105.0,West Virginia:Wirt,1.89,NaN
123761,2019,54107.0,West Virginia:Wood,7.63,-2.14
123762,2019,54109.0,West Virginia:Wyoming,NaN,NaN

In [254]:
df_opioid[["State","County"]] = df_opioid["County"].str.split(":", expand=True)
df_opioid

,Year,FIPS_Code,County,LA_Opioid_Rate,LA_Opioid_Prscrbng_Rate_1Y_Chg,State
3124,2023,54001.0,Barbour,5.41,-1.46,West Virginia
3125,2023,54003.0,Berkeley,8.92,-1.84,West Virginia
3126,2023,54005.0,Boone,1.62,-0.56,West Virginia
3127,2023,54007.0,Braxton,4.30,0.97,West Virginia
3128,2023,54009.0,Brooke,1.72,0.35,West Virginia
...,...,...,...,...,...,...
123758,2019,54101.0,Webster,1.92,-1.85,West Virginia
123759,2019,54103.0,Wetzel,3.04,-1.70,West Virginia
123760,2019,54105.0,Wirt,1.89,NaN,West Virginia
123761,2019,54107.0,Wood,7.63,-2.14,West Virginia
123762,2019,54109.0,Wyoming,NaN,NaN,West Virginia

In [255]:
df_opioid["FIPS_Code"] = df_opioid["FIPS_Code"].astype(int)
df_opioid

,Year,FIPS_Code,County,LA_Opioid_Rate,LA_Opioid_Prscrbng_Rate_1Y_Chg,State
3124,2023,54001,Barbour,5.41,-1.46,West Virginia
3125,2023,54003,Berkeley,8.92,-1.84,West Virginia
3126,2023,54005,Boone,1.62,-0.56,West Virginia
3127,2023,54007,Braxton,4.30,0.97,West Virginia
3128,2023,54009,Brooke,1.72,0.35,West Virginia
...,...,...,...,...,...,...
123758,2019,54101,Webster,1.92,-1.85,West Virginia
123759,2019,54103,Wetzel,3.04,-1.70,West Virginia
123760,2019,54105,Wirt,1.89,NaN,West Virginia
123761,2019,54107,Wood,7.63,-2.14,West Virginia
123762,2019,54109,Wyoming,NaN,NaN,West Virginia

In [256]:
master = df_opioid[[
    "Year",
    "FIPS_Code",
    "State",
    "County",
    "LA_Opioid_Rate",
    "LA_Opioid_Prscrbng_Rate_1Y_Chg"
]]
master

,Year,FIPS_Code,State,County,LA_Opioid_Rate,LA_Opioid_Prscrbng_Rate_1Y_Chg
3124,2023,54001,West Virginia,Barbour,5.41,-1.46
3125,2023,54003,West Virginia,Berkeley,8.92,-1.84
3126,2023,54005,West Virginia,Boone,1.62,-0.56
3127,2023,54007,West Virginia,Braxton,4.30,0.97
3128,2023,54009,West Virginia,Brooke,1.72,0.35
...,...,...,...,...,...,...
123758,2019,54101,West Virginia,Webster,1.92,-1.85
123759,2019,54103,West Virginia,Wetzel,3.04,-1.70
123760,2019,54105,West Virginia,Wirt,1.89,NaN
123761,2019,54107,West Virginia,Wood,7.63,-2.14
123762,2019,54109,West Virginia,Wyoming,NaN,NaN

In [257]:
education_data = education_data.drop(columns=["County"])
master = master.merge(
    education_data,
    on=["Year", "FIPS_Code"],
    how="left"
)
master

,Year,FIPS_Code,State,County,LA_Opioid_Rate,LA_Opioid_Prscrbng_Rate_1Y_Chg,Pct_Less_Than_HS,Pct_HS_Grad,Pct_Bachelors_Plus
0,2023,54001,West Virginia,Barbour,5.41,-1.46,8.0,53.4,12.2
1,2023,54003,West Virginia,Berkeley,8.92,-1.84,6.5,36.9,24.3
2,2023,54005,West Virginia,Boone,1.62,-0.56,10.1,46.8,11.9
3,2023,54007,West Virginia,Braxton,4.30,0.97,10.6,51.1,11.9
4,2023,54009,West Virginia,Brooke,1.72,0.35,5.5,41.5,21.9
...,...,...,...,...,...,...,...,...,...
270,2019,54101,West Virginia,Webster,1.92,-1.85,10.6,49.5,11.4
271,2019,54103,West Virginia,Wetzel,3.04,-1.70,9.9,50.9,12.0
272,2019,54105,West Virginia,Wirt,1.89,NaN,10.4,42.0,11.2
273,2019,54107,West Virginia,Wood,7.63,-2.14,7.2,34.4,21.9
274,2019,54109,West Virginia,Wyoming,NaN,NaN,11.4,48.7,9.3

In [258]:
unemployment_data = unemployment_data.drop(columns=["County"])
master = master.merge(
    unemployment_data,
    on=["Year", "FIPS_Code"],
    how="left"
)
master

,Year,FIPS_Code,State,County,LA_Opioid_Rate,LA_Opioid_Prscrbng_Rate_1Y_Chg,Pct_Less_Than_HS,Pct_HS_Grad,Pct_Bachelors_Plus,Labor_Force_Participation_Rate,Unemployment_Rate,Rural_Urban_Continuum_Code_2023
0,2023,54001,West Virginia,Barbour,5.41,-1.46,8.0,53.4,12.2,50.0,10.3,9
1,2023,54003,West Virginia,Berkeley,8.92,-1.84,6.5,36.9,24.3,66.7,4.8,2
2,2023,54005,West Virginia,Boone,1.62,-0.56,10.1,46.8,11.9,44.4,8.8,3
3,2023,54007,West Virginia,Braxton,4.30,0.97,10.6,51.1,11.9,42.1,12.8,8
4,2023,54009,West Virginia,Brooke,1.72,0.35,5.5,41.5,21.9,54.6,6.0,3
...,...,...,...,...,...,...,...,...,...,...,...,...
270,2019,54101,West Virginia,Webster,1.92,-1.85,10.6,49.5,11.4,47.5,10.6,9
271,2019,54103,West Virginia,Wetzel,3.04,-1.70,9.9,50.9,12.0,46.6,6.2,7
272,2019,54105,West Virginia,Wirt,1.89,NaN,10.4,42.0,11.2,49.4,4.6,3
273,2019,54107,West Virginia,Wood,7.63,-2.14,7.2,34.4,21.9,54.4,4.6,3
274,2019,54109,West Virginia,Wyoming,NaN,NaN,11.4,48.7,9.3,39.9,13.4,8

In [259]:
poverty_data = poverty_data.drop(columns=["County"])
master = master.merge(
    poverty_data,
    on=["Year", "FIPS_Code"],
    how="left"
)
master

,Year,FIPS_Code,State,County,LA_Opioid_Rate,LA_Opioid_Prscrbng_Rate_1Y_Chg,Pct_Less_Than_HS,Pct_HS_Grad,Pct_Bachelors_Plus,Labor_Force_Participation_Rate,Unemployment_Rate,Rural_Urban_Continuum_Code_2023,Poverty_Percent_All_Ages,Poverty_Percent_Age_0_17,Median_Household_Income
0,2023,54001,West Virginia,Barbour,5.41,-1.46,8.0,53.4,12.2,50.0,10.3,9,20.8,29.1,48347
1,2023,54003,West Virginia,Berkeley,8.92,-1.84,6.5,36.9,24.3,66.7,4.8,2,11.4,14.2,77329
2,2023,54005,West Virginia,Boone,1.62,-0.56,10.1,46.8,11.9,44.4,8.8,3,17.3,20.8,56152
3,2023,54007,West Virginia,Braxton,4.30,0.97,10.6,51.1,11.9,42.1,12.8,8,18.8,21.7,44449
4,2023,54009,West Virginia,Brooke,1.72,0.35,5.5,41.5,21.9,54.6,6.0,3,12.1,17.1,52116
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
270,2019,54101,West Virginia,Webster,1.92,-1.85,10.6,49.5,11.4,47.5,10.6,9,26.1,37.4,34927
271,2019,54103,West Virginia,Wetzel,3.04,-1.70,9.9,50.9,12.0,46.6,6.2,7,22.1,34.2,43107
272,2019,54105,West Virginia,Wirt,1.89,NaN,10.4,42.0,11.2,49.4,4.6,3,16.2,23.1,46048
273,2019,54107,West Virginia,Wood,7.63,-2.14,7.2,34.4,21.9,54.4,4.6,3,16.8,24.3,47321
274,2019,54109,West Virginia,Wyoming,NaN,NaN,11.4,48.7,9.3,39.9,13.4,8,22.4,29.4,42332

In [260]:
marital_data = marital_data.drop(columns=["County"])

master = master.merge(
    marital_data,
    on=["Year", "FIPS_Code"],
    how="left"
)
master

,Year,FIPS_Code,State,County,LA_Opioid_Rate,LA_Opioid_Prscrbng_Rate_1Y_Chg,Pct_Less_Than_HS,Pct_HS_Grad,Pct_Bachelors_Plus,Labor_Force_Participation_Rate,Unemployment_Rate,Rural_Urban_Continuum_Code_2023,Poverty_Percent_All_Ages,Poverty_Percent_Age_0_17,Median_Household_Income,Pct_Never_Married,Pct_Divorced
0,2023,54001,West Virginia,Barbour,5.41,-1.46,8.0,53.4,12.2,50.0,10.3,9,20.8,29.1,48347,45.8,10.3
1,2023,54003,West Virginia,Berkeley,8.92,-1.84,6.5,36.9,24.3,66.7,4.8,2,11.4,14.2,77329,48.9,5.3
2,2023,54005,West Virginia,Boone,1.62,-0.56,10.1,46.8,11.9,44.4,8.8,3,17.3,20.8,56152,49.3,8.9
3,2023,54007,West Virginia,Braxton,4.30,0.97,10.6,51.1,11.9,42.1,12.8,8,18.8,21.7,44449,48.2,8.6
4,2023,54009,West Virginia,Brooke,1.72,0.35,5.5,41.5,21.9,54.6,6.0,3,12.1,17.1,52116,44.1,11.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
270,2019,54101,West Virginia,Webster,1.92,-1.85,10.6,49.5,11.4,47.5,10.6,9,26.1,37.4,34927,54.3,7.4
271,2019,54103,West Virginia,Wetzel,3.04,-1.70,9.9,50.9,12.0,46.6,6.2,7,22.1,34.2,43107,45.7,9.4
272,2019,54105,West Virginia,Wirt,1.89,NaN,10.4,42.0,11.2,49.4,4.6,3,16.2,23.1,46048,62.6,5.1
273,2019,54107,West Virginia,Wood,7.63,-2.14,7.2,34.4,21.9,54.4,4.6,3,16.8,24.3,47321,49.7,8.3
274,2019,54109,West Virginia,Wyoming,NaN,NaN,11.4,48.7,9.3,39.9,13.4,8,22.4,29.4,42332,59.7,8.4

In [261]:
master = master[[
    "Year",
    "FIPS_Code",
    "State",
    "County",
    "Labor_Force_Participation_Rate",
    "Unemployment_Rate",
    "Median_Household_Income",
    "Poverty_Percent_All_Ages",
    "Poverty_Percent_Age_0_17",
    "Pct_Never_Married",
    "Pct_Divorced",
    "Pct_Less_Than_HS",
    "Pct_HS_Grad",
    "Pct_Bachelors_Plus",
    "Rural_Urban_Continuum_Code_2023",
    "LA_Opioid_Rate",
    "LA_Opioid_Prscrbng_Rate_1Y_Chg"
]]
master

,Year,FIPS_Code,State,County,Labor_Force_Participation_Rate,Unemployment_Rate,Median_Household_Income,Poverty_Percent_All_Ages,Poverty_Percent_Age_0_17,Pct_Never_Married,Pct_Divorced,Pct_Less_Than_HS,Pct_HS_Grad,Pct_Bachelors_Plus,Rural_Urban_Continuum_Code_2023,LA_Opioid_Rate,LA_Opioid_Prscrbng_Rate_1Y_Chg
0,2023,54001,West Virginia,Barbour,50.0,10.3,48347,20.8,29.1,45.8,10.3,8.0,53.4,12.2,9,5.41,-1.46
1,2023,54003,West Virginia,Berkeley,66.7,4.8,77329,11.4,14.2,48.9,5.3,6.5,36.9,24.3,2,8.92,-1.84
2,2023,54005,West Virginia,Boone,44.4,8.8,56152,17.3,20.8,49.3,8.9,10.1,46.8,11.9,3,1.62,-0.56
3,2023,54007,West Virginia,Braxton,42.1,12.8,44449,18.8,21.7,48.2,8.6,10.6,51.1,11.9,8,4.30,0.97
4,2023,54009,West Virginia,Brooke,54.6,6.0,52116,12.1,17.1,44.1,11.0,5.5,41.5,21.9,3,1.72,0.35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
270,2019,54101,West Virginia,Webster,47.5,10.6,34927,26.1,37.4,54.3,7.4,10.6,49.5,11.4,9,1.92,-1.85
271,2019,54103,West Virginia,Wetzel,46.6,6.2,43107,22.1,34.2,45.7,9.4,9.9,50.9,12.0,7,3.04,-1.70
272,2019,54105,West Virginia,Wirt,49.4,4.6,46048,16.2,23.1,62.6,5.1,10.4,42.0,11.2,3,1.89,NaN
273,2019,54107,West Virginia,Wood,54.4,4.6,47321,16.8,24.3,49.7,8.3,7.2,34.4,21.9,3,7.63,-2.14
274,2019,54109,West Virginia,Wyoming,39.9,13.4,42332,22.4,29.4,59.7,8.4,11.4,48.7,9.3,8,NaN,NaN

In [262]:
master.to_csv("west_virginia_opioid_data.csv", index=False)